### ISSUE TITLE
MMF_04_cap_D3D9 - Exception thrown: read access violation.

### ISSUE THREAD

**Issue by ruhlig** [yephick/2r1y#23] opened 2016-11-30 19:44 UTC
MMF_04_cap_D3D9 app has an Exception thrown: read access violation pSrcPel was 0xBCB00D2 in 2r1y-common\imgxform.cpp in the function TransformImage_YUY2.

This is low priority but making a note of it.

**Comment by yephick** [comment] 2016-12-02 19:38
Won't fix. MM_04_cap_D3D9 is only meant to exist while we test the functions to be implemented on FPGA. The access violation you observed is caused by sloppy error detection in the framework and would take too much (relatively) effort to fix for next to no gain.

**Closed by yephick** 2016-12-02 19:38 UTC
Labels: bug
